/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "secondary-fixed": "#65fbcf",
        "on-surface": "#00184a",
        "on-primary-container": "#004c58",
        "surface-container-low": "#f2f3ff",
        "on-primary-fixed": "#001f25",
        primary: "#006878",
        "tertiary-fixed-dim": "#78dc77",
        "on-secondary-container": "#007057",
        "on-background": "#00184a",
        "inverse-on-surface": "#eef0ff",
        "surface-container-highest": "#dbe1ff",
        "surface-bright": "#faf8ff",
        "surface-tint": "#006878",
        "on-primary": "#ffffff",
        "tertiary-fixed": "#94f990",
        error: "#ba1a1a",
        tertiary: "#006e1c",
        "error-container": "#ffdad6",
        "primary-container": "#0ac4e0",
        "surface-container-high": "#e2e7ff",
        "on-error-container": "#93000a",
        secondary: "#006b54",
        "inverse-surface": "#082b70",
        "surface-dim": "#cfd9ff",
        "on-secondary-fixed": "#002117",
        "primary-fixed-dim": "#3cd8f5",
        "on-error": "#ffffff",
        "secondary-fixed-dim": "#40deb3",
        "on-tertiary-fixed": "#002204",
        "inverse-primary": "#3cd8f5",
        surface: "#faf8ff",
        "surface-container-lowest": "#ffffff",
        outline: "#6c797d",
        "on-secondary": "#ffffff",
        "tertiary-container": "#65c865",
        "on-primary-fixed-variant": "#004e5b",
        background: "#faf8ff",
        "outline-variant": "#bbc9cd",
        "on-tertiary-fixed-variant": "#005313",
        "primary-fixed": "#a6eeff",
        "on-tertiary": "#ffffff",
        "on-surface-variant": "#3c494c",
        "surface-variant": "#dbe1ff",
        "surface-container": "#eaedff",
        "on-tertiary-container": "#005112",
        "on-secondary-fixed-variant": "#00513e",
        "secondary-container": "#61f8cc",
      },
      borderRadius: {
        DEFAULT: "1rem",
        lg: "2rem",
        xl: "3rem",
        full: "9999px",
      },
      fontFamily: {
        headline: ["Manrope", "sans-serif"],
        body: ["Inter", "sans-serif"],
        label: ["Inter", "sans-serif"],
        display: "Manrope",
      },
    },
  },
  plugins: [],
}
